// Generated by CoffeeScript 2.0.0
var TestCase;

TestCase = require("./test-base");

//###############################################################################
// calculation (add,sub) tests
//###############################################################################
exports.test_addition = async function (test) {
	var bot;
	bot = new TestCase(test, `
		+ test counter
		- counter set

		+ show
		- counter = <get counter>

		+ add
		- <add counter=1>adding

		+ sub
		- <sub counter=1>subbing

		+ div
		- <set counter=10>
		^ <div counter=2>
		^ divving

		+ mult
		- <set counter=10>
		^ <mult counter=2>
		^ multing

		+ subtractor
		- <sub subtractor=1>Subtractor is now: <get subtractor>

		+ multiplier
		- <mult multiplier=2>Multiplier is now: <get multiplier>

		+ diviser
		- <div diviser=2>Diviser is now: <get diviser>
	`);
	await bot.reply("test counter", "counter set");
	await bot.reply("show", "counter = undefined");
	await bot.reply("add", "adding");
	await bot.reply("show", "counter = 1");
	await bot.reply("sub", "subbing");
	await bot.reply("show", "counter = 0");
	await bot.reply("div", "divving");
	await bot.reply("show", "counter = 5");
	await bot.reply("mult", "multing");
	await bot.reply("show", "counter = 20");
	await bot.reply("subtractor", "Subtractor is now: -1");
	await bot.reply("subtractor", "Subtractor is now: -2");
	await bot.reply("multiplier", "Multiplier is now: 0");
	await bot.reply("diviser", "Diviser is now: 0");
	await bot.rs.setUservar("localuser", "multiplier", "4");
	await bot.rs.setUservar("localuser", "diviser", "128");
	await bot.reply("multiplier", "Multiplier is now: 8");
	await bot.reply("diviser", "Diviser is now: 64");
	return test.done();
};
